title: Conference Deadlines
description: Countdowns to top SE/NLP/ML/PL conference deadlines
author: snuhcc

domain: "snuhcc.github.io"
baseurl: "https://snuhcc.github.io/conf-deadlines"

github_username: snuhcc
github_repo: conf-deadlines

markdown: kramdown

include: ["_pages"]
